## Task 1

### 1) Write a function to compute 5/0 and use try/except to catch the exceptions

In [103]:
def divide():
    try:
        res=5/0
        print(res)
    except:
        print("divided by Zero exception")
    else:
        print('you got the result')
    finally:
        print("thank you for your support")

In [104]:
divide()

divided by Zero exception
thank you for your support


### 2) Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [22]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [105]:
for s in subjects:
    for v in verbs:
        for o in objects:
            print(s,v,o,sep=" ")

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## Task 2

### 1) Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [109]:
import numpy as np

In [106]:
def matrixform(x,N):
    final=[]
    for i in range(0,N):
        res=[]
        for j in range(0,len(x)): 
            pow=N-i-1
            res.append(x[j]**pow)
        final.append(res)
    print(np.transpose(final))

In [108]:
matrixform([1,2,3,5],3)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
